### PR TITLE
31 hardware tests

### PR DESCRIPTION
**Pull request by mimaxwell**
Simply moved generator test code from /src/generator-src/ to /hardware-tests

### CODE REVIEW

**Comment by mimaxwell** [comment]
Would you prefer a README.md in the hardware-tests or comments at the top of each test file or both?

**Comment by cabeese** [comment]
@mimaxwell Either way is fine with me

**Comment by cabeese** [comment]
@mimaxwell still hoping to get the `boxOne` stuff moved as per earlier comment. Then perhaps add a quick description of it as you did for the others, and then this should be good to merge

**Comment by mimaxwell** [comment]
@Noah, as I'm still working on this issue I'd like to hold off on merging the branch.

**Comment by cabeese** [comment]
@mimaxwell Sounds good. Feel free to re-open this PR or start a new one when your new timing tests are done

**Pull request closed without merging**
